### ISSUE TITLE
Change text and style to provide better UX

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/rcmod-wp-bookings-front-ui#11]
### Problem
Some text and styles in wizard is not clear and should be improved for better UX.

### Solution
- Change the booking wizard's message on top to read as follows: "You are booking: [service name]"
- Modify the placeholder text in the "Additional notes" section of the booking wizard's third step to say: "If you have you got any special requests for this service, please note them down here."
- Fix format in date navigator. Date should look like this: "Monday 12th July"

- Align buttons with header in date navigator.
- Make placeholder text in inputs lighter. 
- Add hover and loading state for buttons.

**Comment by markzahra** [comment]
The placeholder text in the Additional Notes text area is incorrect, there is an extra "you" after "If you have"

**Comment by markzahra** [comment]
The placeholder text in the Additional Notes text area is incorrect, there is an extra "you" after "If you have".
